[package]
name = "nfde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.3", features = ["derive"] }
postgres = "0.19.5"
skim = "0.10.4"
which = "4.4.0"
